# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_laptop_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='Laptops',
        ),
    ]
