# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_auto_20180710_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='LaptopTypes',
        ),
    ]
