# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_auto_20180710_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoptypes',
            name='reviews',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
