# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0006_laptoptypes_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoptypes',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
