# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_laptoptypes_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptoptypes',
            old_name='timestamp',
            new_name='available_time',
        ),
    ]
