# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_auto_20180710_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoptypes',
            name='expiry_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptoptypes',
            name='future_available_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptoptypes',
            name='available_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
